image: gitpod/workspace-nix

tasks:
    - name: Install necessary packages
      command: |
          nix profile install nixpkgs#nixd
          nix profile install nixpkgs#alejandra
          nix profile install nixpkgs#statix
          nix profile install nixpkgs#deadnix
          nix profile install nixpkgs#just
          nix profile install nixpkgs#shellcheck
          nix profile install nixpkgs#shfmt

vscode:
    extensions:
        - jnoortheen.nix-ide
        - kamadorueda.alejandra
        - castrogusttavo.min-theme
        - castrogusttavo.symbols
        - antfu.icons-carbon
        - gruntfuggly.todo-tree
        - mhutchie.git-graph
        - donjayamanne.githistory
        - timonwong.shellcheck
        - foxundermoon.shell-format
        - tyriar.sort-lines
        - yzhang.markdown-all-in-one
        - davidanson.vscode-markdownlint
        - naumovs.color-highlight
        - oderwat.indent-rainbow
        - tamasfe.even-better-toml
        - idleberg.icon-fonts
        - anseki.vscode-color
        - aaron-bond.better-comments
        - ibm.output-colorizer
        - chouzz.vscode-better-align
        - esbenp.prettier-vscode
