name: Lint with statix
on:
  push:
    paths:
      - "**.nix"
  workflow_dispatch:

jobs:
  statix:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: statix
      - uses: jocelynthode/statix-action@master
